# This playbook uses the AWS cli to add routes to a route table because Ansible
# does not merge values into a dictionary.
---
- name: Get Route Table {{ route_table.aws_rt_name }} facts
  include_tasks: get_route_table_facts.yml
  vars:
    rt_region: "{{ route_table.aws_rt_region }}"
    rt_tag: "{{ route_table.aws_rt_name }}"

- name: Create VPC peering route
  block:
    - name: Get VPC peering connection facts
      include_role:
        name: aws_manage_vpc_peer
        tasks_from: "get_vpc_peering_connection_facts"
      vars:
        vpc_pc_tag: "{{ route.target_tag }}"

    - name: Add VPC peering route to Route Table
      command: "aws ec2 create-route --route-table-id {{ rt_facts.route_tables[0].id }} --destination-cidr-block {{ route.dest }} --vpc-peering-connection-id {{ vpc_peering_facts.result[0].vpc_peering_connection_id }}"
      when:
        - ( rt_facts.route_tables | to_json ).find((route.dest)) == -1
        - vpc_peering_facts.result != []

  when: route.target == "vpc-peer"

- name: Create Internet Gateway route
  block:
    - name: Get Internet Gateway facts
      include_role:
        name: aws_manage_igws
        tasks_from: "get_internet_gateway_facts"
      vars:
        vpc_igw_tag: "{{ route.target_tag }}"

    - name: Add Internet Gateway route to Route Table
      command: "aws ec2 create-route --route-table-id {{ rt_facts.route_tables[0].id }} --destination-cidr-block {{ route.dest }} --gateway-id {{ igw_facts.internet_gateways[0].internet_gateway_id }}"
      when:
        - ( rt_facts.route_tables | to_json ).find((route.dest)) == -1
        - igw_facts.internet_gateways != []

  when: route.target == "igw"

- name: Create NAT Gateway route
  block:
    - name: Get NAT Gateway facts
      include_role:
        name: "aws_manage_natgws"
        tasks_from: "get_natgw_facts"
      vars:
        natgw_tag: "{{ route.target_tag }}"

    - name: Add NAT Gateway route to Route Table
      command: "aws ec2 create-route --route-table-id {{ rt_facts.route_tables[0].id }} --destination-cidr-block {{ route.dest }} --gateway-id {{ natgw_facts.result[0].nat_gateway_id }}"
      when:
        - ( rt_facts.route_tables | to_json ).find((route.dest)) == -1
        - natgw_facts.result != []

  when: route.target == "nat"
...
