---
- name: Get VPC {{ route_table.aws_rt_vpc_tag }} facts
  include_role:
    name: "aws_manage_vpc"
    tasks_from: "get_vpc_facts"
  vars:
    vpc_tag: "{{ route_table.aws_rt_vpc_tag }}"

- name: Get Route Table {{ route_table.aws_rt_name }} facts
  include_tasks: get_route_table_facts.yml
  vars:
    rt_region: "{{ route_table.aws_rt_region }}"
    rt_tag: "{{ route_table.aws_rt_name }}"

- name: Set resource name
  set_fact:
    resource_name: "{{ route_table.aws_rt_name | upper }}"

# Ansible module is NOT idempotent - it will overwrite an existing Route Table
- name: Create Route Table
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    vpc_id: "{{ vpc_net_facts.vpcs[0].id }}"
    region: "{{ route_table.aws_rt_region }}"
    tags: "{{ resource_tags }}"
  when: rt_facts.route_tables == []

- name: Add routes to Route Table
  include_tasks: "add_route_to_route_table.yml"
  with_items: "{{ route_table.aws_rt_routes }}"
  loop_control:
    loop_var: route
  when: route_table.aws_rt_routes is defined

- name: Add subnets to Route Table
  include_tasks: "add_subnet_to_route_table.yml"
  with_items: "{{ route_table.aws_rt_subnets }}"
  loop_control:
    loop_var: subnet
  when: route_table.aws_rt_subnets is defined
...
