---
- name: Get Route Table information
  ec2_vpc_route_table_facts:
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    region: "{{ rt_region | default(aws_region) }}"
    filters:
      "tag:Name": "{{ rt_tag | upper }}"
  register: rt_facts
...
